# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :screenshots do
  capture_screenshots
  # frame_screenshots(white: true)
  # upload_to_app_store
end

fastlane_version "2.80.0"

default_platform :ios

ENV["MATCH_PASSWORD"] = "dar"
ENV["FASTLANE_USER"] = "kz.dar.jenkins@gmail.com"
ENV["FASTLANE_PASSWORD"] = "Cicduser112"

def version_bump
  increment_build_number
  # commit_version_bump
  # git_push_to_remote
end

platform :ios do
  changelog = File.read("../Changelog.txt")

  lane :dev_testflight do
    version_bump
    match(app_identifier: "kz.dar.lab.pingoapp", readonly: true)
    gym(scheme: 'yoapp')
    testflight 
  end

end